### ISSUE TITLE
Update IGUANA to 0.3

### ISSUE THREAD

**Issue by k00ni** [Dockerizing/IGUANA#2]
I just got a ping from @TortugaAttack that the IGUANA team released version 0.3 (ours is 0.2). Could you please adapt our Dockerfile to use the latest version?

**Comment by TortugaAttack** [comment]
Please be aware that the configuration has changed a lot! 
Look into the examples to adopt the new settings :)

**Comment by k00ni** [comment]
Thanks for the hint @TortugaAttack!

**Comment by k00ni** [comment]
Is this issue finished @simeonackermann ?

**Comment by k00ni** [comment]
Were the two configuration files adapted? @simeonackermann

**Comment by k00ni** [comment]
Because you said, that the upgrade was not possible (yet), i will close this issue for now. Lets see, if we can fix this later on.
